[tool.poetry]
name = "xi"
version = "0.1.0"
description = ""
authors = ["marco.fumagalli <marco.fumagalli@esprinet.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.2"
pytest = "^7.0"
line-profiler-pycharm = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
